* The English Knowledge You Must Know
** free
*** be free to do/be
#+BEGIN_COMMENT
自由地做/成为...
#+END_COMMENT
- On Facebook, you can *be free to be* who you want to be, as long as you don't mind being bombarded by adverts for the world's biggest brands.
- In Istanbul, women should *be free to* pursue happines and live as they choose, instead of being confined by traditional marriage values, she said.
*** free with : 对...很随意、随便，强调的是“对某事不认真”
- You are too *free with* your manners.
- It seems people become very *free with* their money these days.
*** free of : 免除...，通常指免除租金、债务
- He lived in a flat *free of* rent.
- Westin is rolling out a program at all of its hotels in which guest can borrow New Balence sneakers and workout gear *free of* charge.
*** free from : 摆脱...，从疾病、惧怕、危险或错误等消失或好转，强调从负面的时间中好转
- Even the wise are not always *free from* error.
- You may have another certificate showing the goods to be *free from* radioactive contamination.
- The Thai economy, like many in Asia, sprang *free from* the great recession surprisingly quickly.
** read和read of
*** read : 除了“读、读书”，还有“察觉、了解”的意思
- They're pretty intuitive, and they can see it, they can *read* it.
- Mr Lorry's bussiness eye *read* in the speaker's face that is was loss of time to dwell upon the point.
*** read of : 熟悉，了解
- I *read of* the superstar's marriage in today's newspaper.
- She had, I presume, *read of* how Garfield, Lincoln, and other Americans rose from poverty to fame and greatness.
