* The English Knowledge You Must Know
** be free
*** be free to do/be : 自由地做/成为...
1. On Facebook, you can *be free to be* who you want to be, as long as you don't mind being bombarded by adverts for the world's biggest brands.
2. In Istanbul, women should *be free to* pursue happines and live as they choose, instead of being confined by traditional marriage values, she said.
*** free with : 对...很随意、随便，强调的是“对某事不认真”
1. You are too free with your manners.
2. It seems people become very free with their money these days.
*** free of : 免除...，通常指免除租金、债务
1. He lived in a flat free of rant.
2. Westin is rolling out a program at all of its hotels in which guest can borrow New Balence sneakers and workout gear free of charge.
*** free from : 摆脱...，从疾病、惧怕、危险或错误等消失或好转，强调从负面的时间中好转
1. Even the wise are not always free from error.
2. You may have another certificate showing the goods to be gree from radioactive contamination.
3. The Thai economy, like many in Asia, sprang free from the great recession surprisingly quickly.
